//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int contactID { get; set; }
        public string contactName { get; set; }
        public string contactNo { get; set; }
        public Nullable<System.DateTime> addedOn { get; set; }
    }
}
